### PR TITLE
rgeos - referenced later in the examples

### PR DESCRIPTION
**Pull request by djtfmartin**
.. but not installed in earlier

### CODE REVIEW

**Comment by raymondben** [comment]
Ah, sorry to be the naysayer ... but that particular bit of code (`library(rgeos); wkt <- writeWKT(shape)`) is not actually run. It's shown so that users can see how it *could* be used, but in this case it doesn't help (per the following text) and so that code chunk isn't executed. And the bigger issue is that the `rgeos` package has system dependencies that make it not-straightforward to install in some cases (Linux, possibly other OSes), hence I didn't want to make it a needed package here.

I'd suggest instead that we just expand the text slightly to explain that the code isn't actually run (e.g. replace "We could create the WKT string using the `rgeos` library:" with "We could create the WKT string using the `rgeos` library (code not run here):").

However @PeggyNewman, if you do choose to add `rgeos` here to the vignette, note that you'll also need to add it to the `Suggests:` section of the `DESCRIPTION` file to get checks to pass.

**Comment by raymondben** [comment]
Actually, no, I'm wrong about the `DESCRIPTION` file - it won't need to be added to the that (because that bit of rgeos code isn't actually run, so the package check won't know about it).

@djtfmartin if nothing else I think you have nicely illustrated that my examples could do with a refresh to better explain my cryptic code!!

**Comment by djtfmartin** [comment]
ok - fair enough

**Comment by PeggyNewman** [comment]
Thanks Dave and Ben, noted.

**Pull request closed without merging**
